
edition = "2021"
max_width = 100
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
